// Re-export all entities
export * from './DatosPrestador';
export * from './ServicioSede';
export * from './Autoevaluacion';
export * from './Cumplimiento';
export * from './Criterio';
export * from './Estandar';
export * from './PlanMejora';
export * from './Hallazgo';
export * from './PaginatedResponse';
export * from './SoporteDocumental';
